---
title: "Principal Component Analysis of Cheeses Nutrtion Data"
author: "Carmen Galaz-García"
date: "1/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(ggfortify)  # for PCA
library(janitor)
```

```{r}
# ---- DATA READING ----
food <- read.csv(here("Task2_PCA","usda_nutrients.csv")) %>% 
  clean_names() %>%      
  drop_na()              # remove NA values
```


```{r}
# ----- DATA SELECTION -----
cheeses <- food %>% 
  filter(str_detect(short_descrip, "CHEESE,"),   # select cheeses
         str_detect(food_group, "Dairy") ) %>% 
  select(!(id:short_descrip)) %>%                # select variables used in analysis
  select(!(common_name:scientific_name)) %>% 
  select(descrip:sugar_g) %>% 
  mutate(descrip = str_sub(descrip, start=9)) %>% # remove "cheese" from description
  separate(descrip,                               # separate cheese name from characteristics
           into=c("name", "type"), 
           sep=",", 
           extra="merge") %>%
  filter(!str_detect(name,"fat|pasteurized|sodium")) %>%     # remove "altered" cheeses
  filter(!str_detect(type,"fat|pasteurized|sodium|with|low") | is.na(type)) %>% 
  mutate(origin = case_when(                      # label each cheese by country of origin
    name == "mexican" ~ "mex",
    str_detect(type,"queso")~ "mex",
    str_detect(name,"cheddar|cottage|monterey|muenster|brick|caraway|colby") ~ "us",
    str_detect(name,"fontina|parmesan|mozzarella|provolone|ricotta|romano") ~ "it",
    str_detect(name,"camembert|brie|roquefort|port de salut|blue")~ "fr",
    str_detect(name,"gruyere|neufchatel|swiss|tilsit") ~ "sw",
    str_detect(name,"gouda|edam|limburger") ~ "nth"
  )) %>% 
  relocate(origin)    # group categorical variables at beginning
```

```{r}
# ---- Principal Component Analysis ----
cheeses_PCA <- cheeses %>% 
  select(4:8) %>%    # select numerical variables
  scale() %>% 
  prcomp

cheeses_PCA  
```

```{r}
# ----- BIPLOT -----
autoplot(cheeses_PCA,   # automatically recognizes PCA and does biplot
         data= cheeses,
         colour = 'origin',
#         shape=FALSE,
#         label.size = 2,
         loadings = TRUE,
         loadings.label=TRUE)  +
  theme_minimal()  
```


